apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-sentiment-server-d
  labels:
    app: twitter-sentiment-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: twitter-sentiment-server
        tier: backend
    spec:
      containers:
      - name: twitter-sentiment-server-app
        image: gcr.io/lukegreenleaf-163901/github-gishmel-twitter-sentiment-server
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
