apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: server
  name: server-controller
spec:
  replicas: 2
  selector:
    name: server
  template:
    metadata:
      labels:
        name: server
    spec:
      containers:
      - image: gcr.io/konigshof-162001/konigshof-server
        name: server
        ports:
          - containerPort: 8000
